# Output payloads can be seen at https://webhook.site/#!/7e7e19a5-e875-462d-b5b8-6c46df0d2a98

service: runtime-python-example

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  layers:
    - !Ref ExtensionLambdaLayer
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-extension-internal-python/exec-wrapper.sh
    SLS_OTEL_SERVER_URL: 5038
    SLS_LOG_SERVER_PORT: 2402
    SLS_OTEL_RESOURCE_ATTRIBUTES: 'sls_service_name=${self:service},sls_stage=${sls:stage},sls_org_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    SLS_OTEL_USER_SETTINGS: '{
      "common": {
        "destination": {
          "requestHeaders": "serverless_token=7e492185-581c-4444-a86a-f162d372e398"
        }
      },
      "logs": {
        "destination": "https://webhook.site/#!/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/logs"
      },
      "metrics": {
        "destination": "https://webhook.site/#!/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/metrics"
      },
      "request": {
        "destination": "https://webhook.site/#!/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
      },
      "response": {
        "destination": "https://webhook.site/#!/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
      },
      "traces": {
        "destination": "https://webhook.site/#!/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/traces"
      }
    }'


package:
  individually: true
  patterns:
    - "!**"
    - "handler.py"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

layers:
  extension:
    path: ../assets/extension
    package:
      patterns:
        - '!**'
        - 'extensions/**'
        - 'otel-extension-internal-python/**'

custom:
  pythonRequirements:
    invalidateCaches: true
