[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line_length = 120

[tool.isort]
profile = 'black'
line_length = 120

[tool.mypy]
namespace_packages = true

