from serverless_aws_lambda_otel_extension.shared.environment import TEST_DRY_LOG


SERVERLESS_AWS_LAMBDA_OTEL_EXTENSION_NAME = "serverless-aws-lambda-otel-extension"

AWS_LAMBDA_RUNTIME_API_ENV_VAR = "AWS_LAMBDA_RUNTIME_API"
OTEL_RESOURCE_ATTRIBUTES_ENV_VAR = "OTEL_RESOURCE_ATTRIBUTES"
SLS_LOG_SERVER_HOST_ENV_VAR = "SLS_LOG_SERVER_HOST"
SLS_LOG_SERVER_PORT_ENV_VAR = "SLS_LOG_SERVER_PORT"
SLS_OTEL_RESOURCE_ATTRIBUTES_ENV_VAR = "SLS_OTEL_RESOURCE_ATTRIBUTES"
SLS_OTEL_RESOURCE_ATTRIBUTES_ORG_ID_VAR = "sls_org_id"
SLS_OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME_VAR = "sls_service_name"
SLS_OTEL_RESOURCE_ATTRIBUTES_STAGE_VAR = "sls_stage"
SLS_OTEL_SERVER_HOST_ENV_VAR = "SLS_OTEL_SERVER_HOST"
SLS_OTEL_SERVER_PORT_ENV_VAR = "SLS_OTEL_SERVER_PORT"
TEST_DRY_LOG_ENV_VAR = "TEST_DRY_LOG"

LAMBDA_EXTENSION_NAME_HEADER = "Lambda-Extension-Name"
LAMBDA_EXTENSION_IDENTIFIER_HEADER = "Lambda-Extension-Identifier"
LAMBDA_EXTENSION_FUNCTION_ERROR_TYPE_HEADER = "Lambda-Extension-Function-Error-Type"

EXTENSIONS_API_EVENT_NEXT_PATH = "2020-01-01/extension/event/next"
EXTENSIONS_API_EXIT_ERROR_PATH = "2020-01-01/extension/exit/error"
EXTENSIONS_API_INIT_ERROR_PATH = "2020-01-01/extension/init/error"
EXTENSIONS_API_REGISTER_PATH = "2020-01-01/extension/register"

LOGS_API_PATH = "2020-08-15/logs"

HTTP_CONTENT_TYPE_APPLICATION_JSON = "application/json"
HTTP_CONTENT_TYPE_HEADER = "Content-Type"

HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POST"
HTTP_METHOD_PUT = "PUT"
