DEFAULT_OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT = 100

DEFAULT_SLS_OTEL_SERVER_HOST = "sandbox.localdomain"
DEFAULT_SLS_OTEL_SERVER_PORT = 2772

DEFAULT_SLS_LOG_SERVER_HOST = "sandbox.localdomain"
DEFAULT_SLS_LOG_SERVER_PORT = 4243

DEFAULT_SLS_OTEL_RESOURCE_ATTRIBUTES_ORG_ID = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
DEFAULT_SLS_OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME = "undefined"
DEFAULT_SLS_OTEL_RESOURCE_ATTRIBUTES_STAGE = "undefined"
